### ISSUE TITLE
ES6 Classes

### ISSUE THREAD

**Issue by mpolinowski** [scotchfield/elasticsearch-react-example#3]
Hi @scotchfield ,

First - thank you for this repo. It is just what I was looking for!

But due to the **createClass** deprecation, it does not work anymore :(

1.) I added my ElasticSearch 5.x Index to the query - and it works with in **"react": "^0.14.5"** beautifully:

https://github.com/mpolinowski/elasticsearch-react-example#update-to-a-elasticsearch-5x-index

2.) But I cannot get it to work in **React v16** - I am getting an error message about propTypes/defaultProps:

https://github.com/mpolinowski/elasticsearch-react-example#es6-class-syntax

Do you have an idea what I am doing wrong there? I tried a couple of StackOverflow solutions... but I am stuck right now. 

Cheers Mike

**Comment by scotchfield** [comment]
Hi @mpolinowski, and thanks for reaching out! I'm sorry that this hasn't been updated in a while.

I took a stab at bringing the project in-line with React 16, and it seems to be working here. Can you try pulling the latest change and see if that fixes things for you? If not, let me know, and I'll try to help you get things sorted out. :)

Have a nice day!

**Comment by mpolinowski** [comment]
Hi Scott,

thanks for getting back right away :) I checked your code and found my 3 problems - the ES6 classes are now up and running. Thx, Awesome!

But right now I don't get a render on those \<li\>'s :

https://github.com/scotchfield/elasticsearch-react-example/blob/64e2f388d09c1564c44039e389b8e370567239ea/src/app.js#L50

Search results from ES are there and \<ul\>\</ul\> Element from \<SearchResults /\> shows up - but the result map is missing. I am looking into it right now - is all of this running on your side?

**Comment by mpolinowski** [comment]
Hi Scott,

I found the issue - the event handler had to be bound:

https://github.com/mpolinowski/elasticsearch-react-example/blob/7c7a6296b23a7f3fca093d45f8f98eb8cdc2ccb5/src/app.js#L18

It works now, after adding this line to the \<App /\> constructor.

Again, thank you for your help - this repo helped me a lot :)

Cheers

**Comment by scotchfield** [comment]
Hey Mike, thanks for the update! Sorry for not getting back to your second question earlier. Glad you were able to find the root of the problem. :)

Take care!
